Integrated Mayhem
mayhemheroes/pulsarctl pull request #1
Opened 2022-05-26 02:12 UTC by bmwtsn098

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

2022-07-27 07:19 UTC, xansec requested changes
Please make the requested changes.

2022-07-27 07:19 UTC, xansec commented on Dockerfile
> +# Build Stage:
Can we add a package stage here?

2022-07-27 07:19 UTC, xansec commented on Mayhemfile
> +# Namespaced project name that the target belongs to
Multiple commands are not supported unless you are fuzzing both instrumented and uninstrumented calls of the same binary. I would either remove the extra commands or split into multiple Mayhemfiles. Be sure to also genericize the project name and omit the image.

2022-07-29 04:55 UTC, bmwtsn098 commented
I've made the requested changes. Let me know if everything looks good. Thanks

2022-08-01 15:41 UTC, xansec approved these changes
LGTM!

2022-08-01 15:41 UTC, merged